# Generated by Django 2.2.6 on 2020-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='no_of_members',
            field=models.IntegerField(default=0),
        ),
    ]
