# Generated by Django 2.2.6 on 2020-02-19 06:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200217_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='parent_group',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='sub_groups',
        ),
        migrations.AddField(
            model_name='cohort',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainapp.Cohort'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohort',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
