# Generated by Django 2.2.6 on 2020-02-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200211_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subgroups',
        ),
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.IntegerField(default=0),
        ),
    ]
