# Generated by Django 2.2.6 on 2020-02-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200211_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Cohort',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='target_group',
            new_name='target_cohort',
        ),
    ]
