# Generated by Django 2.2.6 on 2020-02-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200228_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
