# Generated by Django 2.2.6 on 2020-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200228_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
