# Generated by Django 2.2.6 on 2020-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_question_total_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
