# Generated by Django 2.2.6 on 2020-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
