# Generated by Django 2.2.6 on 2020-05-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_reply_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='time',
            new_name='timestamp',
        ),
    ]
