# Generated by Django 2.2.6 on 2020-05-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200524_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='timestamp',
            new_name='time',
        ),
    ]
