# Generated by Django 2.2.6 on 2020-05-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200524_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='total_answers',
        ),
    ]
