# Generated by Django 2.2.6 on 2020-05-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='no_of_members',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='total_posts',
        ),
    ]
