# Generated by Django 2.2.6 on 2020-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200531_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='group_logos'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images'),
        ),
    ]
