# Generated by Django 2.2.6 on 2020-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20200531_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
