# Generated by Django 2.2.6 on 2020-06-27 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0020_auto_20200531_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='members',
            field=models.ManyToManyField(related_name='cohorts', related_query_name='cohort', to=settings.AUTH_USER_MODEL),
        ),
    ]
