# Generated by Django 3.0.5 on 2020-07-06 12:51

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_cohort_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NP', 'New Post'), ('NM', 'New Message'), ('NC', 'New Comment'), ('NR', 'New Reply')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.Question'),
        ),
    ]
