# Generated by Django 2.2.6 on 2019-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default='18:47', verbose_name='Time'),
        ),
    ]
