# Generated by Django 2.2.6 on 2020-03-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200223_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='unread_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='unread_B',
            field=models.IntegerField(default=0),
        ),
    ]
