# Generated by Django 2.2.6 on 2020-05-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200523_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='time',
        ),
    ]
