# Generated by Django 2.2.6 on 2020-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200526_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_A',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_B',
            field=models.BooleanField(default=False),
        ),
    ]
