# Generated by Django 2.2.6 on 2019-12-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20191218_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default='03:07', max_length=10),
        ),
    ]
