# Generated by Django 2.2.6 on 2020-05-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200527_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
