# Generated by Django 2.2.6 on 2019-12-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20191218_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default='03:09', max_length=10),
        ),
    ]
