# Generated by Django 2.2.6 on 2020-05-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='unread_A',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='unread_B',
        ),
    ]
