# Generated by Django 2.2.6 on 2019-12-18 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20191218_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default='14:07', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 14, 7, 50, 456590, tzinfo=utc)),
        ),
    ]
