# Generated by Django 2.2.6 on 2019-12-19 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20191218_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default='08:50', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 8, 50, 31, 760532, tzinfo=utc)),
        ),
    ]
