# Generated by Django 2.2.6 on 2019-12-19 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20191219_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=models.ForeignKey(default=datetime.datetime(2019, 12, 19, 16, 36, 18, 494635, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_last_message', to='chat.Message'),
        ),
    ]
