# Generated by Django 2.2.6 on 2020-02-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.FileField(upload_to='profile_photos')),
                ('study_field', models.CharField(max_length=250)),
                ('user_groups', models.TextField()),
            ],
        ),
    ]
