# Generated by Django 2.2.6 on 2020-02-19 06:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200217_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
