# Generated by Django 2.2.6 on 2020-02-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200215_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(default='C:\\Users\\John YK\\Desktop\\projects\\CohMat\\media\\profile_photos/default_profile_pic.png', upload_to='profile_photos'),
        ),
    ]
