# Generated by Django 2.2.6 on 2020-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200417_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(default='C:\\Users\\John YK\\PycharmProjects\\CollegeNet\\media\\profile_photos/default_profile_pic.png', upload_to='profile_photos'),
        ),
    ]
