# Generated by Django 2.2.6 on 2020-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200522_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_count',
            field=models.IntegerField(default=0),
        ),
    ]
