# Generated by Django 2.2.6 on 2020-05-27 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200523_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
