# Generated by Django 2.2.6 on 2020-05-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_notification_seen'),
        ('accounts', '0014_auto_20200528_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_groups',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_cohorts',
            field=models.ManyToManyField(related_name='user_cohorts', to='mainapp.Cohort'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='study_field', to='mainapp.Cohort'),
        ),
    ]
