# Generated by Django 2.2.6 on 2020-05-31 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200530_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_current_interest', to='mainapp.Cohort'),
        ),
    ]
