# Generated by Django 2.2.6 on 2020-06-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200531_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_cohorts',
        ),
    ]
